# Generated by Django 5.0.1 on 2024-01-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
