# Generated by Django 5.0.1 on 2024-01-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_finch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(blank=True, to='main_app.toy'),
        ),
    ]
