# Generated by Django 5.0.1 on 2024-01-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_finch_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='finch',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
